gateway:
  scheme: http
  host: localhost
  port: 8080

api:
  prefix: /api/v1
  urn:
    problem: problem
    solution: solution
    user: user
    evaluation: evaluation

server:
  port: 8081

custom:
  value: 0
